CREATE TABLE IF NOT EXISTS users (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS identity,
    username TEXT NOT NULL UNIQUE,
    email TEXT NOT NULL UNIQUE,
	password VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);
